{% set name = "quast" %}
{% set version = "4.6.1" %}
{% set hash = "29118bff957af6d1b36136735450ddc8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1 
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: http://downloads.sourceforge.net/project/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  md5: {{ hash }}

requirements:
  build:
    - gcc
    - boost {{CONDA_BOOST}}*
    - perl
    - python
    - matplotlib
    - openjdk
    - joblib
    - simplejson

  run:
    - boost {{CONDA_BOOST}}*
    - perl
    - python
    - libgcc
    - matplotlib
    - openjdk
    - joblib
    - simplejson
    - barrnap
    - bedtools
    - busco
    - bwa
    #- genemark
    #- genemark-es
    - glimmer
    - gnuplot
    - krona
    #- lap
    - minimap2
    - sambamba

test:
  source_files:
    - test_data
  commands:
    - quast --version
    - quast --test
    - metaquast --version
    - metaquast --test

about:
  home: https://sourceforge.net/projects/{{ name|lower }}/
  license: GPL2
  license_file: LICENSE.txt
  summary: Quality Assessment Tool for Genome Assemblies
