{% set name = "quast" %}
{% set version = "4.6.1" %}
{% set hash = "29118bff957af6d1b36136735450ddc8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0 
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: http://downloads.sourceforge.net/project/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  md5: {{ hash }}
  patches:
    - gnuplot-issue_disable-mummer-plots.patch 
    - genemark-issue_disable-and-exclude-from-package.patch

requirements:
  build:
    - gcc
    - boost {{CONDA_BOOST}}*
    - perl
    - python
    - matplotlib
    - openjdk
    - joblib
    - simplejson

  run:
    - boost {{CONDA_BOOST}}*
    - perl
    - python
    - libgcc
    - matplotlib
    - openjdk
    - joblib
    - simplejson

test:
  source_files:
    - test_data
  commands:
    - quast --version
    - metaquast --version

about:
  home: https://sourceforge.net/projects/{{ name|lower }}/
  license: GPL2
  license_file: LICENSE.txt
  summary: Quality Assessment Tool for Genome Assemblies

extra:
  notes: 
    - drawing MUMmer plots is disabled due to issues with gnuplot
    - GeneMark gene prediction software is disabled due to licensing issues
