package:
  name: bio_assembly_refinement
  version: "0.5.0"

source:
  fn: bio_assembly_refinement-0.5.0.tar.gz
  url: https://pypi.python.org/packages/source/b/bio_assembly_refinement/bio_assembly_refinement-0.5.0.tar.gz
  md5: 93657bf827b05d033fd33215ace8e197

build:
  skip: True # [py27]
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pyfastaq >=3.10.0
    - pymummer

  run:
    - python
    - pyfastaq >=3.10.0
    - pymummer

test:
  imports:
    - bio_assembly_refinement

  requires:
    - nose >=1.3

about:
  home: https://github.com/nds/bio_assembly_refinement
  license: GPLv3
  summary: 'Assembly refinement tools, mostly useful for (but not limited to) pacbio bacterial assemblies'
